services:
  - type: worker
    name: discord-bot
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
